### ISSUE TITLE
Add node_modules and bower_components to .gitignore

### ISSUE THREAD

**Issue by hhzl** [HeSe/amber-processingJs#2]
The directories ``node_modules`` and ``bower_components`` do not need to be in the master branch.

They are populated by

       npm install
       bower install

as the [README](https://github.com/HeSe/amber-processingJs/blob/master/README.md) states.

For a ``.gitignore`` example
see https://github.com/amber-smalltalk/amber-examples/blob/master/.gitignore 

Display of example
------------------------

Another case is not to exclude the two directories in  the gh-pages branch so that you can display your example live as

http://hese.github.io/amber-processingJS

**Comment by HeSe** [comment]
Thank you for the hint. I added the file and removed the folders to ignore.
